### ISSUE TITLE
如果原文在引号后还有代码的情况下似乎无法读取到引号内的文本

### ISSUE THREAD

**Issue by epq1176** [libudu/renpy-deepl#1]
如果原文在引号后还有代码的情况下似乎无法读取到引号内的文本

**Comment by libudu** [comment]
啥叫在引号后还有代码哦，可以给个样例吗

**Comment by epq1176** [comment]
nurse surprised "[mc]?! What in god's name?!" with vpunch
像是这种就不能提取出中间的文本

**Comment by libudu** [comment]
![image](https://user-images.githubusercontent.com/52157213/202750180-08a2b9ee-10ed-4d83-98c9-1a5864c7536f.png)
已修复
