### ISSUE TITLE
deepl 翻译中文花括号{i}{/i}丢失 错误

### ISSUE THREAD

**Issue by yexiaozhulin** [libudu/renpy-deepl#2]
大佬，deepl 翻译中文花括号老丢失和出错。就是这种{i}{/i} 能不能翻译前去掉翻译后自动加回来

**Comment by libudu** [comment]
![image](https://user-images.githubusercontent.com/52157213/202750908-1cbd5782-d340-4d32-875e-8401c8b83d76.png)
这个真要处理会很麻烦细节。看了一下好像一般deepl是能当成特殊字符处理的，你的用例是咋样的哦。

**Comment by yexiaozhulin** [comment]
也不是都这样。
 # p "{i}This is getting weird...{/i}"
    p "{这事越来越奇怪了......{/i}。"
    # p "{i}What did I just get myself into?{/i}"
    p "{我刚刚把自己卷入了什么？"

    # p "{i}Looks like I'm not the only one that thinks this is bullshit.{/i}"
    p "{i}看来我不是唯一认为这是胡闹的人。"

    # p "{i}What the fuck do I say? I'll have to make something up...{/i}"
    p "{我他妈的该说什么？我得编点什么......{/i}。"

    # p "{i}My own army of sex crazed girls... Awesome!{/i}"
    p "{我自己的性爱大军... 真棒！{/i}"
有的时候{}里面是字母乱码

**Comment by yexiaozhulin** [comment]
有款翻译姬软件 正则文本处理规则\{[^\{\}+]+\}|[　!?—&\(\)“”{}] 能把所有符号选出来 翻译完不知道怎么又能放回去，
就是用的翻译国内api 老漏翻译，翻译质量也如deepl

**Comment by libudu** [comment]
要不这种还是手动处理一下吧。情况比较特殊，如果符号是存在文字之间的，没办法知道翻译前后对应的单词，也就没可能对应上。就算知道了要做也挺麻烦的。
