### ISSUE TITLE
这种字符是不是不识别

### ISSUE THREAD

**Issue by yexiaozhulin** [libudu/renpy-deepl#3]
translate chinese strings:

    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "I like it when you give me blowjobs and footjobs."
    new "I like it when you give me blowjobs and footjobs."

    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "I really enjoy fucking you."
    new "I really enjoy fucking you."

    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "Can I enjoy both ways?"
    new "Can I enjoy both ways?"

translate chinese strings:
    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "I like it when you give me blowjobs and footjobs."
    new "I like it when you give me blowjobs and footjobs."
    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "I really enjoy fucking you."
    new "I really enjoy fucking you."
    # game/scripts/characters/julia/julia_scenes.rpy:1658
    old "Can I enjoy both ways?"
    new "Can I enjoy both ways?"

**Comment by libudu** [comment]
是，视频里有提到，不过已经在考虑要不要支持一下了
