### ISSUE TITLE
输入代码，粘贴 翻译的文件 提示 红色的英文错误

### ISSUE THREAD

**Issue by freeacer** [libudu/renpy-deepl#4]
输入代码，粘贴 翻译的文件 提示 红色的英文错误

Uncaught TypeError: Cannot read property 'value' of undefined
at <anonymous>:72:25
at o (sentry.min.$314a47.js:2)
(anonymous) @ VM54:72
o @ sentry.min.$314a47.js:2
setInterval (async)
(anonymous) @ sentry.min.$314a47.js:2
(anonymous) @ VM54:71

**Comment by libudu** [comment]
修了，你再试试
